### ISSUE TITLE
Threading

### ISSUE THREAD

**Issue by newaddressunknown** [Lucas-Bruder/ESP32_LED_STRIP#14]
Do you have experience with threading. After starting a new thread 
`xTaskCreate(&start_rainbow, "start_led", 2048, NULL, 5, &led_task_handle);`

with the following method
```
void start_led(void *pvParameters)
{
    struct led_strip_t led_strip = {
        .rgb_led_type = RGB_LED_TYPE_WS2812,
        .rmt_channel = RMT_CHANNEL_1,
        .rmt_interrupt_num = LED_STRIP_RMT_INTR_NUM,
        .gpio = GPIO_NUM_14,
        .led_strip_buf_1 = led_strip_buf_1,
        .led_strip_buf_2 = led_strip_buf_2,
        .led_strip_length = LED_STRIP_LENGTH
    };
    led_strip.access_semaphore = xSemaphoreCreateBinary();
    bool led_init_ok = led_strip_init(&led_strip);
    assert(led_init_ok);

    struct led_color_t led_color = {
        .red = 5,
        .green = 0,
        .blue = 0,
    };

    while (xSemaphoreTake(led_mutex, ( TickType_t ) 10 ) == pdTRUE ) {
      xSemaphoreGive(led_mutex);
      ESP_LOGI(TAG, "RUNNING led thread");

      for (uint32_t index = 0; index < LED_STRIP_LENGTH; index++) {
        led_strip_set_pixel_color(&led_strip, index, &led_color);
      }
      led_strip_show(&led_strip);    
      vTaskDelay(60 / portTICK_PERIOD_MS);
    }

    /*
    exit and cleanup
    */
    ESP_LOGI(TAG, "STOPPING led thread");
    led_strip_clear(&led_strip);
    vTaskDelete(NULL);
}
```
I get  the following error after starting the thread, stopping it with the mutex and starting it again.
```
E (40094) RMT: /home/bud/workspace/ESP32/esp-idf/components/driver/./rmt.c:702 (rmt_wait_tx_done):RMT CHANNEL ERR        
/home/bud/workspace/ESP32/esp-idf/components/freertos/./queue.c:1445 (xQueueGenericReceive)- assert failed!
Guru Meditation Error: Core   0 panic'ed (Unhandled debug exception)
```
Would it perhaps be possible to implement a "destructor" for the led_strip?
BTW: Thank you for the library.

**Comment by Lucas-Bruder** [comment]
Yes, adding a destructor might fix this. I'll dig into this this weekend. Can you send me all of your code?

**Comment by newaddressunknown** [comment]
I just pushed it. [https://github.com/budb/ESP32-LED-SERVER](url) (link doesn't work)
Includes a small server to control the LED Strip, or in my case hopefully soon a matrix; also the rainbow effect.
Still very rough. Will add a todo-list and polish tomorrow.

**Comment by Lucas-Bruder** [comment]
thanks. ill work on getting a led_strip_delete function this weekend

**Comment by Lucas-Bruder** [comment]
hey @budb can you explain what you're trying to acomplish by dynamically creating led strips? what is the reason for killing the task used to drive the LEDs?

**Comment by newaddressunknown** [comment]
The idea was to start a new task if I change the mode. For example from the rainbow colors to static or to blinking. But you are most likely right. I could also do with changing the mode through ipc. I am sorry for some errors (dynamically creating the strips) and will fix them. The last time I did C was 1 1/2 years ago in uni. If you have any further suggestions I would be glad.  

One more thing. Do you want the rainbow mode as an example on a high level, or inside the library? (Might be a new issue to discuss)

**Comment by Lucas-Bruder** [comment]
Ah yes, you can keep the led strip going and just set the colors to 0.

For the rainbow, I'm working on getting an examples folder setup with the build system.  The idea would then to be have a bunch of examples that people could pull from, and I would remove the main.c file in the main folder so that I could work on my own main file without effecting others. I'm currently working on an animation library so you can start animations and define how fast you want them to move. That might be a good place to include the rainbow code.

**Comment by Lucas-Bruder** [comment]
Hey I have a branch setup with it, but can't get it to function correctly. I'm going to put this on the back burner for now; it looks like it may be deep in the RMT driver and theres a few other things I want to work on before spending time on this.

The branch in progress is lucas/delete_led_strip if you want to check it out and mess with it. 

In the meantime, I'd suggest keeping the led strip open and not trying to delete any tasks associated with it.
